(function () {
  const app = window.ICTApp;

  app.data = {
    games: {
      build: { title: "Computer Island", subtitle: "Build, match, and tap.", duration: "8 to 10 minutes" },
      input: { title: "Input Island", subtitle: "Sort, choose, and go fast.", duration: "8 to 10 minutes" },
      output: { title: "Output Island", subtitle: "Name it and choose it.", duration: "8 to 10 minutes" },
      challenge: { title: "Challenge Island", subtitle: "Listen, tap, or wait.", duration: "10 to 12 minutes" },
      fun: { title: "Fun Zone", subtitle: "Bonus games unlocked!", duration: "Free play" },
    },
    buildParts: [
      { id: "monitor", label: "Monitor", emoji: "🖥️", hint: "Shows pictures", zone: "monitor" },
      { id: "keyboard", label: "Keyboard", emoji: "⌨️", hint: "Helps you type", zone: "keyboard" },
      { id: "mouse", label: "Mouse", emoji: "🖱️", hint: "Moves and clicks", zone: "mouse" },
      { id: "system", label: "Computer", asset: "assets/computer.svg", hint: "Runs the computer", zone: "system" },
    ],
    buildFunctions: [
      { id: "type", label: "Type", emoji: "✍️", target: "keyboard" },
      { id: "see", label: "See", emoji: "👀", target: "monitor" },
      { id: "click", label: "Click", emoji: "👉", target: "mouse" },
      { id: "think", label: "Brain", emoji: "⚙️", target: "system" },
    ],
    buildPrompts: [
      { clue: "Tap the part we use to TYPE.", answer: "keyboard" },
      { clue: "Tap the part that SHOWS the work.", answer: "monitor" },
      { clue: "Tap the part that MOVES the arrow.", answer: "mouse" },
      { clue: "Tap the COMPUTER.", answer: "system" },
      { clue: "Tap the part you usually look AT.", answer: "monitor" },
    ],
    sortDeck: [
      { id: "keyboard", label: "Keyboard", emoji: "⌨️", type: "input" },
      { id: "mouse", label: "Mouse", emoji: "🖱️", type: "input" },
      { id: "microphone", label: "Microphone", emoji: "🎤", type: "input" },
      { id: "webcam", label: "Webcam", emoji: "📷", type: "input" },
      { id: "touchscreen", label: "Touch Screen", emoji: "📱", type: "input" },
      { id: "speaker", label: "Speaker", emoji: "🔊", type: "output" },
      { id: "monitor", label: "Monitor", emoji: "🖥️", type: "output" },
      { id: "printer", label: "Printer", emoji: "🖨️", type: "output" },
      { id: "projector", label: "Projector", emoji: "📽️", type: "output" },
      { id: "headphones", label: "Headphones", emoji: "🎧", type: "output" },
    ],
    inputScenarios: [
      { text: "Voice in?", answer: "input" },
      { text: "Music out?", answer: "output" },
      { text: "Type name?", answer: "input" },
      { text: "See picture?", answer: "output" },
      { text: "Photo in?", answer: "input" },
      { text: "Print page?", answer: "output" },
    ],
    outputQuestions: [
      { item: "Keyboard", emoji: "⌨️", prompt: "What does it do?", correct: "Type", options: ["Type", "Hear", "Sleep"] },
      { item: "Mouse", emoji: "🖱️", prompt: "What does it do?", correct: "Move", options: ["Move", "Print", "Sing"] },
      { item: "Monitor", emoji: "🖥️", prompt: "What does it do?", correct: "See", options: ["See", "Eat", "Jump"] },
      { item: "Speaker", emoji: "🔊", prompt: "What does it do?", correct: "Hear", options: ["Hear", "Type", "Photo"] },
      { item: "Printer", emoji: "🖨️", prompt: "What does it do?", correct: "Print", options: ["Print", "Talk", "Record"] },
      { item: "Microphone", emoji: "🎤", prompt: "What does it do?", correct: "Talk", options: ["Talk", "See", "Dance"] },
      { item: "Webcam", emoji: "📷", prompt: "What does it do?", correct: "Photo", options: ["Photo", "Music", "Move"] },
      { item: "Headphones", emoji: "🎧", prompt: "What does it do?", correct: "Hear", options: ["Hear", "Print", "Food"] },
    ],
    outputScenarios: [
      { text: "Big wall video?", correct: "Projector", options: ["Projector", "Mouse", "Keyboard"] },
      { text: "Hear story?", correct: "Headphones", options: ["Headphones", "Printer", "Webcam"] },
      { text: "Paper page?", correct: "Printer", options: ["Printer", "Speaker", "Microphone"] },
      { text: "See game?", correct: "Monitor", options: ["Monitor", "Mouse", "Microphone"] },
      { text: "Play music?", correct: "Speaker", options: ["Speaker", "Keyboard", "Touch Screen"] },
      { text: "Take class photo?", correct: "Webcam", options: ["Webcam", "Printer", "Speaker"] },
    ],
    challengeRounds: [
      { says: true, prompt: "Teacher says touch the keyboard!", answer: "keyboard" },
      { says: true, prompt: "Teacher says touch something you can SEE!", answer: "monitor" },
      { says: false, prompt: "Touch the mouse!", answer: "wait" },
      { says: true, prompt: "Teacher says touch something that gives SOUND!", answer: "speaker" },
      { says: true, prompt: "Teacher says touch the microphone!", answer: "microphone" },
      { says: false, prompt: "Touch the monitor!", answer: "wait" },
      { says: true, prompt: "Teacher says touch something used to TYPE!", answer: "keyboard" },
      { says: true, prompt: "Teacher says touch the mouse!", answer: "mouse" },
      { says: false, prompt: "Touch something that prints!", answer: "wait" },
      { says: true, prompt: "Teacher says touch the printer!", answer: "printer" },
    ],
    challengeTargets: [
      { id: "keyboard", label: "Keyboard", emoji: "⌨️" },
      { id: "mouse", label: "Mouse", emoji: "🖱️" },
      { id: "monitor", label: "Monitor", emoji: "🖥️" },
      { id: "speaker", label: "Speaker", emoji: "🔊" },
      { id: "microphone", label: "Microphone", emoji: "🎤" },
      { id: "printer", label: "Printer", emoji: "🖨️" },
      { id: "wait", label: "Wait!", emoji: "✋" },
    ],
    moodChoices: [
      { id: "happy", emoji: "😄", label: "Happy", path: "emoji" },
      { id: "excited", emoji: "🤩", label: "Excited", path: "emoji" },
      { id: "okay", emoji: "🙂", label: "Okay", path: "emoji" },
      { id: "sleepy", emoji: "😴", label: "Sleepy", path: "mindful" },
      { id: "sad", emoji: "😢", label: "Sad", path: "mindful" },
      { id: "angry", emoji: "😠", label: "Angry", path: "mindful" },
    ],
    emojiGameRounds: [
      { target: "😄", options: ["😄", "😎", "😆", "🥳"] },
      { target: "🤩", options: ["🤩", "😴", "😊", "🥰"] },
      { target: "🥳", options: ["🥳", "😢", "😄", "😮"] },
    ],
    calmSteps: [
      { title: "Smell the flower", emoji: "🌸", text: "Breathe in slow." },
      { title: "Blow the candle", emoji: "🕯️", text: "Breathe out slow." },
      { title: "Stretch your arms", emoji: "👐", text: "Reach up high." },
      { title: "Shake it out", emoji: "✨", text: "Tiny wiggle shake." },
    ],
    sillyMessages: ["Boing! Silly tap!", "Splash! A funny fish!", "Twinkle! A happy star!", "Wiggle wiggle!", "Haha! Try the game too!"],
    confettiColors: ["#ff5d8f", "#ffd84f", "#4cc9f0", "#2ec27e", "#ff8e3c", "#a78bfa"],
  };
})();
