(function () {
  var app = window.ICTApp = window.ICTApp || {};

  app.data = {
    games: {
      build: { title: "Computer Island", subtitle: "Build, match, and tap.", duration: "8 to 10 minutes" },
      input: { title: "Input Island", subtitle: "Sort, choose, and go fast.", duration: "8 to 10 minutes" },
      output: { title: "Output Island", subtitle: "Name it and choose it.", duration: "8 to 10 minutes" },
      challenge: { title: "Challenge Island", subtitle: "Listen, tap, or wait.", duration: "10 to 12 minutes" },
      onoff: { title: "Lesson 2: Turn It On / Off", subtitle: "Wake, wait, save, and shut down safely.", duration: "45 to 50 minutes" },
      fun: { title: "Fun Zone", subtitle: "Bonus games unlocked!", duration: "Free play" },
    },
    lessonMenu: [
      { id: "lesson1", title: "Lesson 1", subtitle: "ICT Adventure Island", emoji: "🌴" },
      { id: "lesson2", title: "Lesson 2", subtitle: "Turn On / Off", emoji: "🔘" },
      { id: "games", title: "Play Games", subtitle: "Fun Zone Arcade", emoji: "🎮" }
    ],
    unitMenu: [
      {
        id: "unit1",
        title: "Unit 1: Computer Basics",
        color: "green",
        emoji: "🖥️",
        range: "Lessons 1-15",
        lessons: [
          { id: "lesson1", number: 1, title: "ICT Adventure Island", subtitle: "Parts and simple computer skills", emoji: "🌴", active: true },
          { id: "lesson2", number: 2, title: "Turning a Computer On/Off", subtitle: "Wake, wait, save, and shut down", emoji: "🔘", active: true },
          { id: "coming-parts-review", number: 3, title: "Parts of a Computer Review Game", subtitle: "Coming Soon", emoji: "🧩", active: false },
          { id: "coming-tablet-computer", number: 4, title: "What is a Tablet vs Computer", subtitle: "Coming Soon", emoji: "📱", active: false },
          { id: "coming-laptop-desktop", number: 5, title: "Laptop vs Desktop", subtitle: "Coming Soon", emoji: "💻", active: false },
          { id: "coming-screen-use", number: 6, title: "What is the Screen Used For", subtitle: "Coming Soon", emoji: "🖼️", active: false },
          { id: "coming-mouse-use", number: 7, title: "What is a Mouse Used For", subtitle: "Coming Soon", emoji: "🖱️", active: false },
          { id: "coming-keyboard-use", number: 8, title: "What is a Keyboard Used For", subtitle: "Coming Soon", emoji: "⌨️", active: false },
          { id: "coming-speaker", number: 9, title: "What is a Speaker / Sound", subtitle: "Coming Soon", emoji: "🔊", active: false },
          { id: "coming-printer", number: 10, title: "What is a Printer", subtitle: "Coming Soon", emoji: "🖨️", active: false },
          { id: "coming-internet", number: 11, title: "What is the Internet", subtitle: "Coming Soon", emoji: "🌐", active: false },
          { id: "coming-wifi", number: 12, title: "What is Wi-Fi", subtitle: "Coming Soon", emoji: "📶", active: false },
          { id: "coming-file", number: 13, title: "What is a File", subtitle: "Coming Soon", emoji: "📄", active: false },
          { id: "coming-folder", number: 14, title: "What is a Folder", subtitle: "Coming Soon", emoji: "📁", active: false },
          { id: "coming-safety", number: 15, title: "Computer Safety Basics", subtitle: "Coming Soon", emoji: "🛡️", active: false }
        ]
      },
      {
        id: "unit2",
        title: "Unit 2: Input & Interaction",
        color: "blue",
        emoji: "🖱️",
        range: "Lessons 16-30",
        lessons: [
          { id: "u2-16", number: 16, title: "Click vs Double Click", subtitle: "Coming Soon", emoji: "👆", active: false },
          { id: "u2-17", number: 17, title: "Drag and Drop Skills", subtitle: "Coming Soon", emoji: "🧲", active: false },
          { id: "u2-18", number: 18, title: "Typing Letters", subtitle: "Coming Soon", emoji: "🔤", active: false },
          { id: "u2-19", number: 19, title: "Typing Simple Words", subtitle: "Coming Soon", emoji: "🔡", active: false },
          { id: "u2-20", number: 20, title: "Using the Space Bar", subtitle: "Coming Soon", emoji: "↔️", active: false },
          { id: "u2-21", number: 21, title: "Using Enter Key", subtitle: "Coming Soon", emoji: "↩️", active: false },
          { id: "u2-22", number: 22, title: "Using Backspace", subtitle: "Coming Soon", emoji: "⬅️", active: false },
          { id: "u2-23", number: 23, title: "Using Arrow Keys", subtitle: "Coming Soon", emoji: "🔼", active: false },
          { id: "u2-24", number: 24, title: "Touchscreen vs Mouse", subtitle: "Coming Soon", emoji: "👆", active: false },
          { id: "u2-25", number: 25, title: "Drawing with a Mouse", subtitle: "Coming Soon", emoji: "🎨", active: false },
          { id: "u2-26", number: 26, title: "Drawing with Touch", subtitle: "Coming Soon", emoji: "🖍️", active: false },
          { id: "u2-27", number: 27, title: "Keyboard Games", subtitle: "Coming Soon", emoji: "🎹", active: false },
          { id: "u2-28", number: 28, title: "Mouse Accuracy Game", subtitle: "Coming Soon", emoji: "🎯", active: false },
          { id: "u2-29", number: 29, title: "Speed Clicking Game", subtitle: "Coming Soon", emoji: "⚡", active: false },
          { id: "u2-30", number: 30, title: "Basic Typing Game", subtitle: "Coming Soon", emoji: "⌨️", active: false }
        ]
      },
      {
        id: "unit3",
        title: "Unit 3: Creating Content",
        color: "yellow",
        emoji: "🎨",
        range: "Lessons 31-45",
        lessons: [
          { id: "u3-31", number: 31, title: "Drawing a Picture (Paint App)", subtitle: "Coming Soon", emoji: "🖌️", active: false },
          { id: "u3-32", number: 32, title: "Using Colors", subtitle: "Coming Soon", emoji: "🌈", active: false },
          { id: "u3-33", number: 33, title: "Using Shapes", subtitle: "Coming Soon", emoji: "🔷", active: false },
          { id: "u3-34", number: 34, title: "Using Eraser Tool", subtitle: "Coming Soon", emoji: "🧽", active: false },
          { id: "u3-35", number: 35, title: "Making a Simple Poster", subtitle: "Coming Soon", emoji: "🪧", active: false },
          { id: "u3-36", number: 36, title: "Adding Text to a Picture", subtitle: "Coming Soon", emoji: "🔠", active: false },
          { id: "u3-37", number: 37, title: "Changing Font Size", subtitle: "Coming Soon", emoji: "🔡", active: false },
          { id: "u3-38", number: 38, title: "Creating a Name Tag", subtitle: "Coming Soon", emoji: "🏷️", active: false },
          { id: "u3-39", number: 39, title: "Making a Birthday Card", subtitle: "Coming Soon", emoji: "🎂", active: false },
          { id: "u3-40", number: 40, title: "Drawing a House", subtitle: "Coming Soon", emoji: "🏠", active: false },
          { id: "u3-41", number: 41, title: "Drawing a Computer", subtitle: "Coming Soon", emoji: "🖥️", active: false },
          { id: "u3-42", number: 42, title: "Copy and Paste", subtitle: "Coming Soon", emoji: "📋", active: false },
          { id: "u3-43", number: 43, title: "Save a File", subtitle: "Coming Soon", emoji: "💾", active: false },
          { id: "u3-44", number: 44, title: "Open a File", subtitle: "Coming Soon", emoji: "📂", active: false },
          { id: "u3-45", number: 45, title: "Print a Picture", subtitle: "Coming Soon", emoji: "🖨️", active: false }
        ]
      },
      {
        id: "unit4",
        title: "Unit 4: Understanding Media",
        color: "purple",
        emoji: "🎬",
        range: "Lessons 46-60",
        lessons: [
          { id: "u4-46", number: 46, title: "What is a Photo", subtitle: "Coming Soon", emoji: "📷", active: false },
          { id: "u4-47", number: 47, title: "What is a Video", subtitle: "Coming Soon", emoji: "🎥", active: false },
          { id: "u4-48", number: 48, title: "What is Music", subtitle: "Coming Soon", emoji: "🎵", active: false },
          { id: "u4-49", number: 49, title: "Playing a Video", subtitle: "Coming Soon", emoji: "▶️", active: false },
          { id: "u4-50", number: 50, title: "Pausing and Playing", subtitle: "Coming Soon", emoji: "⏯️", active: false },
          { id: "u4-51", number: 51, title: "Volume Control", subtitle: "Coming Soon", emoji: "🔉", active: false },
          { id: "u4-52", number: 52, title: "Taking a Screenshot", subtitle: "Coming Soon", emoji: "📸", active: false },
          { id: "u4-53", number: 53, title: "What is a Camera", subtitle: "Coming Soon", emoji: "📹", active: false },
          { id: "u4-54", number: 54, title: "Taking a Photo", subtitle: "Coming Soon", emoji: "🤳", active: false },
          { id: "u4-55", number: 55, title: "Recording Sound", subtitle: "Coming Soon", emoji: "🎙️", active: false },
          { id: "u4-56", number: 56, title: "Listening to Audio", subtitle: "Coming Soon", emoji: "🎧", active: false },
          { id: "u4-57", number: 57, title: "What is Animation", subtitle: "Coming Soon", emoji: "✨", active: false },
          { id: "u4-58", number: 58, title: "Simple Frame Animation", subtitle: "Coming Soon", emoji: "🌀", active: false },
          { id: "u4-59", number: 59, title: "Watching Educational Videos", subtitle: "Coming Soon", emoji: "📺", active: false },
          { id: "u4-60", number: 60, title: "Creating a Slideshow", subtitle: "Coming Soon", emoji: "🖼️", active: false }
        ]
      },
      {
        id: "unit5",
        title: "Unit 5: Internet Basics",
        color: "orange",
        emoji: "🌐",
        range: "Lessons 61-75",
        lessons: [
          { id: "u5-61", number: 61, title: "What is a Website", subtitle: "Coming Soon", emoji: "🕸️", active: false },
          { id: "u5-62", number: 62, title: "Opening a Browser", subtitle: "Coming Soon", emoji: "🧭", active: false },
          { id: "u5-63", number: 63, title: "What is Google", subtitle: "Coming Soon", emoji: "🔎", active: false },
          { id: "u5-64", number: 64, title: "Searching for Pictures", subtitle: "Coming Soon", emoji: "🖼️", active: false },
          { id: "u5-65", number: 65, title: "Searching for Videos", subtitle: "Coming Soon", emoji: "🎞️", active: false },
          { id: "u5-66", number: 66, title: "Safe Searching", subtitle: "Coming Soon", emoji: "🛡️", active: false },
          { id: "u5-67", number: 67, title: "What is a Link", subtitle: "Coming Soon", emoji: "🔗", active: false },
          { id: "u5-68", number: 68, title: "Clicking Links", subtitle: "Coming Soon", emoji: "🖱️", active: false },
          { id: "u5-69", number: 69, title: "What is an Email", subtitle: "Coming Soon", emoji: "✉️", active: false },
          { id: "u5-70", number: 70, title: "What is Online Safety", subtitle: "Coming Soon", emoji: "🔒", active: false },
          { id: "u5-71", number: 71, title: "Stranger Danger Online", subtitle: "Coming Soon", emoji: "🚫", active: false },
          { id: "u5-72", number: 72, title: "Asking Before Clicking", subtitle: "Coming Soon", emoji: "🙋", active: false },
          { id: "u5-73", number: 73, title: "Good vs Bad Websites", subtitle: "Coming Soon", emoji: "⚖️", active: false },
          { id: "u5-74", number: 74, title: "What is a Password", subtitle: "Coming Soon", emoji: "🔑", active: false },
          { id: "u5-75", number: 75, title: "Keeping Information Safe", subtitle: "Coming Soon", emoji: "🧠", active: false }
        ]
      },
      {
        id: "unit6",
        title: "Unit 6: Logic & Coding Foundations",
        color: "red",
        emoji: "🧠",
        range: "Lessons 76-90",
        lessons: [
          { id: "u6-76", number: 76, title: "What is a Step-by-Step Instruction", subtitle: "Coming Soon", emoji: "👣", active: false },
          { id: "u6-77", number: 77, title: "Giving Instructions Game", subtitle: "Coming Soon", emoji: "🗣️", active: false },
          { id: "u6-78", number: 78, title: "Following Instructions Game", subtitle: "Coming Soon", emoji: "✅", active: false },
          { id: "u6-79", number: 79, title: "What is a Pattern", subtitle: "Coming Soon", emoji: "🔁", active: false },
          { id: "u6-80", number: 80, title: "Pattern Recognition Game", subtitle: "Coming Soon", emoji: "🟦", active: false },
          { id: "u6-81", number: 81, title: "Sequencing Game", subtitle: "Coming Soon", emoji: "1️⃣", active: false },
          { id: "u6-82", number: 82, title: "If / Then Thinking", subtitle: "Coming Soon", emoji: "🤔", active: false },
          { id: "u6-83", number: 83, title: "Cause and Effect", subtitle: "Coming Soon", emoji: "💡", active: false },
          { id: "u6-84", number: 84, title: "Simple Maze Logic", subtitle: "Coming Soon", emoji: "🌀", active: false },
          { id: "u6-85", number: 85, title: "Intro to Block Coding", subtitle: "Coming Soon", emoji: "🧱", active: false },
          { id: "u6-86", number: 86, title: "Move a Character", subtitle: "Coming Soon", emoji: "🏃", active: false },
          { id: "u6-87", number: 87, title: "Make a Character Jump", subtitle: "Coming Soon", emoji: "🦘", active: false },
          { id: "u6-88", number: 88, title: "Add Sound to Character", subtitle: "Coming Soon", emoji: "🔔", active: false },
          { id: "u6-89", number: 89, title: "Create a Mini Story", subtitle: "Coming Soon", emoji: "📖", active: false },
          { id: "u6-90", number: 90, title: "Build a Simple Game", subtitle: "Coming Soon", emoji: "🎮", active: false }
        ]
      }
    ],
    buildParts: [
      { id: "monitor", label: "Monitor", asset: "assets/monitor.svg", hint: "Shows pictures", zone: "monitor" },
      { id: "keyboard", label: "Keyboard", asset: "assets/keyboard.svg", hint: "Helps you type", zone: "keyboard" },
      { id: "mouse", label: "Mouse", asset: "assets/mouse.svg", hint: "Moves and clicks", zone: "mouse" },
      { id: "system", label: "Computer", asset: "assets/computer.svg", hint: "Runs the computer", zone: "system" },
    ],
    buildFunctions: [
      { id: "type", label: "Type", emoji: "✍️", target: "keyboard" },
      { id: "see", label: "See", emoji: "👀", target: "monitor" },
      { id: "click", label: "Click", emoji: "👉", target: "mouse" },
      { id: "think", label: "Brain", emoji: "⚙️", target: "system" },
    ],
    buildPrompts: [
      { clue: "Tap the part we use to TYPE.", answer: "keyboard" },
      { clue: "Tap the part that SHOWS the work.", answer: "monitor" },
      { clue: "Tap the part that MOVES the arrow.", answer: "mouse" },
      { clue: "Tap the COMPUTER.", answer: "system" },
      { clue: "Tap the part you usually look AT.", answer: "monitor" },
    ],
    sortDeck: [
      { id: "keyboard", label: "Keyboard", emoji: "⌨️", type: "input" },
      { id: "mouse", label: "Mouse", emoji: "🖱️", type: "input" },
      { id: "microphone", label: "Microphone", emoji: "🎤", type: "input" },
      { id: "webcam", label: "Webcam", emoji: "📷", type: "input" },
      { id: "touchscreen", label: "Touch Screen", emoji: "📱", type: "input" },
      { id: "speaker", label: "Speaker", emoji: "🔊", type: "output" },
      { id: "monitor", label: "Monitor", emoji: "🖥️", type: "output" },
      { id: "printer", label: "Printer", emoji: "🖨️", type: "output" },
      { id: "projector", label: "Projector", emoji: "📽️", type: "output" },
      { id: "headphones", label: "Headphones", emoji: "🎧", type: "output" },
    ],
    inputScenarios: [
      { text: "Voice in?", answer: "input" },
      { text: "Music out?", answer: "output" },
      { text: "Type name?", answer: "input" },
      { text: "See picture?", answer: "output" },
      { text: "Photo in?", answer: "input" },
      { text: "Print page?", answer: "output" },
    ],
    outputQuestions: [
      { item: "Keyboard", emoji: "⌨️", prompt: "What does it do?", correct: "Type", options: ["Type", "Hear", "Sleep"] },
      { item: "Mouse", emoji: "🖱️", prompt: "What does it do?", correct: "Move", options: ["Move", "Print", "Sing"] },
      { item: "Monitor", emoji: "🖥️", prompt: "What does it do?", correct: "See", options: ["See", "Eat", "Jump"] },
      { item: "Speaker", emoji: "🔊", prompt: "What does it do?", correct: "Hear", options: ["Hear", "Type", "Photo"] },
      { item: "Printer", emoji: "🖨️", prompt: "What does it do?", correct: "Print", options: ["Print", "Talk", "Record"] },
      { item: "Microphone", emoji: "🎤", prompt: "What does it do?", correct: "Talk", options: ["Talk", "See", "Dance"] },
      { item: "Webcam", emoji: "📷", prompt: "What does it do?", correct: "Photo", options: ["Photo", "Music", "Move"] },
      { item: "Headphones", emoji: "🎧", prompt: "What does it do?", correct: "Hear", options: ["Hear", "Print", "Food"] },
    ],
    outputScenarios: [
      { text: "Big wall video?", correct: "Projector", options: ["Projector", "Mouse", "Keyboard"] },
      { text: "Hear story?", correct: "Headphones", options: ["Headphones", "Printer", "Webcam"] },
      { text: "Paper page?", correct: "Printer", options: ["Printer", "Speaker", "Microphone"] },
      { text: "See game?", correct: "Monitor", options: ["Monitor", "Mouse", "Microphone"] },
      { text: "Play music?", correct: "Speaker", options: ["Speaker", "Keyboard", "Touch Screen"] },
      { text: "Take class photo?", correct: "Webcam", options: ["Webcam", "Printer", "Speaker"] },
    ],
    challengeRounds: [
      { says: true, prompt: "Teacher says touch the keyboard!", answer: "keyboard" },
      { says: true, prompt: "Teacher says touch something you can SEE!", answer: "monitor" },
      { says: false, prompt: "Touch the mouse!", answer: "wait" },
      { says: true, prompt: "Teacher says touch something that gives SOUND!", answer: "speaker" },
      { says: true, prompt: "Teacher says touch the microphone!", answer: "microphone" },
      { says: false, prompt: "Touch the monitor!", answer: "wait" },
      { says: true, prompt: "Teacher says touch something used to TYPE!", answer: "keyboard" },
      { says: true, prompt: "Teacher says touch the mouse!", answer: "mouse" },
      { says: false, prompt: "Touch something that prints!", answer: "wait" },
      { says: true, prompt: "Teacher says touch the printer!", answer: "printer" },
    ],
    challengeTargets: [
      { id: "keyboard", label: "Keyboard", asset: "assets/keyboard.svg" },
      { id: "mouse", label: "Mouse", asset: "assets/mouse.svg" },
      { id: "monitor", label: "Monitor", asset: "assets/monitor.svg" },
      { id: "speaker", label: "Speaker", emoji: "🔊" },
      { id: "microphone", label: "Microphone", emoji: "🎤" },
      { id: "printer", label: "Printer", emoji: "🖨️" },
      { id: "wait", label: "Wait!", emoji: "✋" },
    ],
    moodChoices: [
      { id: "happy", emoji: "😄", label: "Happy", path: "emoji" },
      { id: "excited", emoji: "🤩", label: "Excited", path: "emoji" },
      { id: "okay", emoji: "🙂", label: "Okay", path: "emoji" },
      { id: "sleepy", emoji: "😴", label: "Sleepy", path: "mindful" },
      { id: "sad", emoji: "😢", label: "Sad", path: "mindful" },
      { id: "angry", emoji: "😠", label: "Angry", path: "mindful" },
    ],
    emojiGameRounds: [
      { target: "😄", options: ["😄", "😎", "😆", "🥳"] },
      { target: "🤩", options: ["🤩", "😴", "😊", "🥰"] },
      { target: "🥳", options: ["🥳", "😢", "😄", "😮"] },
    ],
    calmSteps: [
      { id: "flower", title: "Smell the flower", emoji: "🌸", text: "Breathe in through your nose.", helper: "Smell the flower. Big slow breath in." },
      { id: "candle", title: "Blow the candle", emoji: "🕯️", text: "Breathe out very slow.", helper: "Blow the candle. Long slow breath out." },
      { id: "stretch", title: "Stretch up high", emoji: "👐", text: "Reach your hands up to the sky.", helper: "Stretch your arms. Make your body long." },
      { id: "shake", title: "Shake it out", emoji: "✨", text: "Small shake. Let the grumpy feelings go.", helper: "Shake your hands and shoulders." },
    ],
    onoffWakeTargets: [
      { id: "plug", label: "Plug In", emoji: "🔌", hint: "Power first." },
      { id: "button", label: "Power Button", emoji: "🔘", hint: "Press to wake." },
      { id: "screen", label: "Screen On", emoji: "💡", hint: "Now we can see." }
    ],
    onoffSteps: [
      { id: "plug", label: "Plug in", emoji: "🔌" },
      { id: "press", label: "Press power", emoji: "🔘" },
      { id: "wait", label: "Wait", emoji: "⏳" },
      { id: "login", label: "Log in", emoji: "🙂" },
      { id: "work", label: "Start work", emoji: "🖥️" }
    ],
    onoffWakeChecks: [
      { text: "The screen lights up. Tap SCREEN ON.", answer: "screen", options: [{ id: "screen", label: "Screen On", emoji: "💡" }, { id: "off", label: "Still Off", emoji: "🌙" }, { id: "sleep", label: "Sleep", emoji: "😴" }] },
      { text: "Now the child needs to get in. Tap LOG IN.", answer: "login", options: [{ id: "restart", label: "Restart", emoji: "🔄" }, { id: "login", label: "Log In", emoji: "🙂" }, { id: "run", label: "Run Away", emoji: "🏃" }] },
      { text: "The computer is ready. Tap START WORK.", answer: "work", options: [{ id: "work", label: "Start Work", emoji: "🖥️" }, { id: "turn_off", label: "Turn Off", emoji: "⏻" }, { id: "dance", label: "Dance", emoji: "💃" }] },
      { text: "One last check. Tap WAIT while the computer gets ready.", answer: "wait", options: [{ id: "wait", label: "Wait", emoji: "⏳" }, { id: "smash", label: "Smash Keys", emoji: "⌨️" }, { id: "sleep", label: "Sleep", emoji: "😴" }] }
    ],
    onoffStepChecks: [
      { text: "What comes first?", answer: "plug", options: ["plug", "work", "login"] },
      { text: "What comes after plug in?", answer: "press", options: ["wait", "press", "turn_off"] },
      { text: "After press power, what next?", answer: "wait", options: ["wait", "work", "sleep"] },
      { text: "When the computer wakes up, what next?", answer: "login", options: ["login", "turn_off", "plug"] },
      { text: "What is the last step?", answer: "work", options: ["restart", "work", "wait"] }
    ],
    onoffScenarios: [
      { text: "You want to start computer class.", answer: "turn_on", options: [{ id: "turn_on", label: "Turn On", emoji: "🔘" }, { id: "sleep", label: "Sleep", emoji: "😴" }, { id: "restart", label: "Restart", emoji: "🔄" }] },
      { text: "You finished your drawing. What first?", answer: "save_first", options: [{ id: "save_first", label: "Save", emoji: "💾" }, { id: "turn_off", label: "Turn Off", emoji: "⏻" }, { id: "run", label: "Run Away", emoji: "🏃" }] },
      { text: "Time to go home.", answer: "turn_off", options: [{ id: "turn_off", label: "Turn Off", emoji: "⏻" }, { id: "turn_on", label: "Turn On", emoji: "🔘" }, { id: "dance", label: "Dance", emoji: "💃" }] },
      { text: "Computer is stuck. Try this.", answer: "restart", options: [{ id: "restart", label: "Restart", emoji: "🔄" }, { id: "sleep", label: "Sleep", emoji: "😴" }, { id: "save_first", label: "Save", emoji: "💾" }] },
      { text: "Short break. Come back soon.", answer: "sleep", options: [{ id: "sleep", label: "Sleep", emoji: "😴" }, { id: "turn_off", label: "Turn Off", emoji: "⏻" }, { id: "restart", label: "Restart", emoji: "🔄" }] },
      { text: "Work is open. Do this before off.", answer: "save_first", options: [{ id: "restart", label: "Restart", emoji: "🔄" }, { id: "save_first", label: "Save", emoji: "💾" }, { id: "turn_off", label: "Turn Off", emoji: "⏻" }] }
    ],
    onoffRoutineRounds: [
      { text: "The computer is dark. What now?", answer: "turn_on" },
      { text: "You pressed power. Next?", answer: "wait" },
      { text: "Your game is open. Before off?", answer: "save_first" },
      { text: "Class is over.", answer: "turn_off" },
      { text: "Quick break only.", answer: "sleep" },
      { text: "Computer froze.", answer: "restart" },
      { text: "Screen wakes up. Now?", answer: "login" },
      { text: "You want to use the computer.", answer: "turn_on" },
      { text: "Work is done and saved.", answer: "turn_off" },
      { text: "Power light is on. Be patient.", answer: "wait" },
      { text: "You are back from lunch fast. Best choice?", answer: "sleep" },
      { text: "The class wants to begin computer time.", answer: "turn_on" },
      { text: "The screen shows your file. Before shutting down?", answer: "save_first" },
      { text: "Everything is frozen and will not move.", answer: "restart" },
      { text: "The login page is on the screen. What now?", answer: "login" }
    ],
    onoffRoutineChoices: [
      { id: "turn_on", label: "Turn On", emoji: "🔘" },
      { id: "wait", label: "Wait", emoji: "⏳" },
      { id: "save_first", label: "Save", emoji: "💾" },
      { id: "turn_off", label: "Turn Off", emoji: "⏻" },
      { id: "sleep", label: "Sleep", emoji: "😴" },
      { id: "restart", label: "Restart", emoji: "🔄" },
      { id: "login", label: "Log In", emoji: "🙂" }
    ],
    sillyMessages: ["Boing! Silly tap!", "Splash! A funny fish!", "Twinkle! A happy star!", "Wiggle wiggle!", "Haha! Try the game too!"],
    confettiColors: ["#ff5d8f", "#ffd84f", "#4cc9f0", "#2ec27e", "#ff8e3c", "#a78bfa"],
  };
})();
