(function () {
  var app = window.ICTApp = window.ICTApp || {};

  app.data = {
    games: {
      build: { title: "Computer Island", subtitle: "Build, match, and tap.", duration: "8 to 10 minutes" },
      input: { title: "Input Island", subtitle: "Sort, choose, and go fast.", duration: "8 to 10 minutes" },
      output: { title: "Output Island", subtitle: "Name it and choose it.", duration: "8 to 10 minutes" },
      challenge: { title: "Challenge Island", subtitle: "Listen, tap, or wait.", duration: "10 to 12 minutes" },
      onoff: { title: "Lesson 2: Turn It On / Off", subtitle: "Wake, wait, save, and shut down safely.", duration: "45 to 50 minutes" },
      fun: { title: "Fun Zone", subtitle: "Bonus games unlocked!", duration: "Free play" },
    },
    lessonMenu: [
      { id: "lesson1", title: "Lesson 1", subtitle: "ICT Adventure Island", emoji: "🌴" },
      { id: "lesson2", title: "Lesson 2", subtitle: "Turn On / Off", emoji: "🔘" },
      { id: "games", title: "Play Games", subtitle: "Fun Zone Arcade", emoji: "🎮" }
    ],
    unitMenu: [
      {
        id: "unit1",
        title: "Unit 1: Computer Basics",
        color: "green",
        emoji: "🖥️",
        range: "Lessons 1-15",
        lessons: [
          { id: "lesson1", number: 1, title: "ICT Adventure Island", subtitle: "Parts and simple computer skills", emoji: "🌴", active: true },
          { id: "lesson2", number: 2, title: "Turning a Computer On/Off", subtitle: "Wake, wait, save, and shut down", emoji: "🔘", active: true },
          { id: "coming-parts-review", number: 3, title: "Parts of a Computer Review Game", subtitle: "Coming Soon", emoji: "🧩", active: false },
          { id: "coming-tablet-computer", number: 4, title: "What is a Tablet vs Computer", subtitle: "Coming Soon", emoji: "📱", active: false },
          { id: "coming-laptop-desktop", number: 5, title: "Laptop vs Desktop", subtitle: "Coming Soon", emoji: "💻", active: false },
          { id: "coming-screen-use", number: 6, title: "What is the Screen Used For", subtitle: "Coming Soon", emoji: "🖼️", active: false },
          { id: "coming-mouse-use", number: 7, title: "What is a Mouse Used For", subtitle: "Coming Soon", emoji: "🖱️", active: false },
          { id: "coming-keyboard-use", number: 8, title: "What is a Keyboard Used For", subtitle: "Coming Soon", emoji: "⌨️", active: false },
          { id: "coming-speaker", number: 9, title: "What is a Speaker / Sound", subtitle: "Coming Soon", emoji: "🔊", active: false },
          { id: "coming-printer", number: 10, title: "What is a Printer", subtitle: "Coming Soon", emoji: "🖨️", active: false },
          { id: "coming-internet", number: 11, title: "What is the Internet", subtitle: "Coming Soon", emoji: "🌐", active: false },
          { id: "coming-wifi", number: 12, title: "What is Wi-Fi", subtitle: "Coming Soon", emoji: "📶", active: false },
          { id: "coming-file", number: 13, title: "What is a File", subtitle: "Coming Soon", emoji: "📄", active: false },
          { id: "coming-folder", number: 14, title: "What is a Folder", subtitle: "Coming Soon", emoji: "📁", active: false },
          { id: "coming-safety", number: 15, title: "Computer Safety Basics", subtitle: "Coming Soon", emoji: "🛡️", active: false }
        ]
      },
      {
        id: "unit2",
        title: "Unit 2: Input & Interaction",
        color: "blue",
        emoji: "🖱️",
        range: "Lessons 16-30",
        lessons: [
          { id: "u2-16", number: 16, title: "Click vs Double Click", subtitle: "Coming Soon", emoji: "👆", active: false },
          { id: "u2-17", number: 17, title: "Drag and Drop Skills", subtitle: "Coming Soon", emoji: "🧲", active: false },
          { id: "u2-18", number: 18, title: "Typing Letters", subtitle: "Coming Soon", emoji: "🔤", active: false },
          { id: "u2-19", number: 19, title: "Typing Simple Words", subtitle: "Coming Soon", emoji: "🔡", active: false },
          { id: "u2-20", number: 20, title: "Using the Space Bar", subtitle: "Coming Soon", emoji: "↔️", active: false },
          { id: "u2-21", number: 21, title: "Using Enter Key", subtitle: "Coming Soon", emoji: "↩️", active: false },
          { id: "u2-22", number: 22, title: "Using Backspace", subtitle: "Coming Soon", emoji: "⬅️", active: false },
          { id: "u2-23", number: 23, title: "Using Arrow Keys", subtitle: "Coming Soon", emoji: "🔼", active: false },
          { id: "u2-24", number: 24, title: "Touchscreen vs Mouse", subtitle: "Coming Soon", emoji: "👆", active: false },
          { id: "u2-25", number: 25, title: "Drawing with a Mouse", subtitle: "Coming Soon", emoji: "🎨", active: false },
          { id: "u2-26", number: 26, title: "Drawing with Touch", subtitle: "Coming Soon", emoji: "🖍️", active: false },
          { id: "u2-27", number: 27, title: "Keyboard Games", subtitle: "Coming Soon", emoji: "🎹", active: false },
          { id: "u2-28", number: 28, title: "Mouse Accuracy Game", subtitle: "Coming Soon", emoji: "🎯", active: false },
          { id: "u2-29", number: 29, title: "Speed Clicking Game", subtitle: "Coming Soon", emoji: "⚡", active: false },
          { id: "u2-30", number: 30, title: "Basic Typing Game", subtitle: "Coming Soon", emoji: "⌨️", active: false }
        ]
      },
      {
        id: "unit3",
        title: "Unit 3: Creating Content",
        color: "yellow",
        emoji: "🎨",
        range: "Lessons 31-45",
        lessons: [
          { id: "u3-31", number: 31, title: "Drawing a Picture (Paint App)", subtitle: "Coming Soon", emoji: "🖌️", active: false },
          { id: "u3-32", number: 32, title: "Using Colors", subtitle: "Coming Soon", emoji: "🌈", active: false },
          { id: "u3-33", number: 33, title: "Using Shapes", subtitle: "Coming Soon", emoji: "🔷", active: false },
          { id: "u3-34", number: 34, title: "Using Eraser Tool", subtitle: "Coming Soon", emoji: "🧽", active: false },
          { id: "u3-35", number: 35, title: "Making a Simple Poster", subtitle: "Coming Soon", emoji: "🪧", active: false },
          { id: "u3-36", number: 36, title: "Adding Text to a Picture", subtitle: "Coming Soon", emoji: "🔠", active: false },
          { id: "u3-37", number: 37, title: "Changing Font Size", subtitle: "Coming Soon", emoji: "🔡", active: false },
          { id: "u3-38", number: 38, title: "Creating a Name Tag", subtitle: "Coming Soon", emoji: "🏷️", active: false },
          { id: "u3-39", number: 39, title: "Making a Birthday Card", subtitle: "Coming Soon", emoji: "🎂", active: false },
          { id: "u3-40", number: 40, title: "Drawing a House", subtitle: "Coming Soon", emoji: "🏠", active: false },
          { id: "u3-41", number: 41, title: "Drawing a Computer", subtitle: "Coming Soon", emoji: "🖥️", active: false },
          { id: "u3-42", number: 42, title: "Copy and Paste", subtitle: "Coming Soon", emoji: "📋", active: false },
          { id: "u3-43", number: 43, title: "Save a File", subtitle: "Coming Soon", emoji: "💾", active: false },
          { id: "u3-44", number: 44, title: "Open a File", subtitle: "Coming Soon", emoji: "📂", active: false },
          { id: "u3-45", number: 45, title: "Print a Picture", subtitle: "Coming Soon", emoji: "🖨️", active: false }
        ]
      },
      {
        id: "unit4",
        title: "Unit 4: Understanding Media",
        color: "purple",
        emoji: "🎬",
        range: "Lessons 46-60",
        lessons: [
          { id: "u4-46", number: 46, title: "What is a Photo", subtitle: "Coming Soon", emoji: "📷", active: false },
          { id: "u4-47", number: 47, title: "What is a Video", subtitle: "Coming Soon", emoji: "🎥", active: false },
          { id: "u4-48", number: 48, title: "What is Music", subtitle: "Coming Soon", emoji: "🎵", active: false },
          { id: "u4-49", number: 49, title: "Playing a Video", subtitle: "Coming Soon", emoji: "▶️", active: false },
          { id: "u4-50", number: 50, title: "Pausing and Playing", subtitle: "Coming Soon", emoji: "⏯️", active: false },
          { id: "u4-51", number: 51, title: "Volume Control", subtitle: "Coming Soon", emoji: "🔉", active: false },
          { id: "u4-52", number: 52, title: "Taking a Screenshot", subtitle: "Coming Soon", emoji: "📸", active: false },
          { id: "u4-53", number: 53, title: "What is a Camera", subtitle: "Coming Soon", emoji: "📹", active: false },
          { id: "u4-54", number: 54, title: "Taking a Photo", subtitle: "Coming Soon", emoji: "🤳", active: false },
          { id: "u4-55", number: 55, title: "Recording Sound", subtitle: "Coming Soon", emoji: "🎙️", active: false },
          { id: "u4-56", number: 56, title: "Listening to Audio", subtitle: "Coming Soon", emoji: "🎧", active: false },
          { id: "u4-57", number: 57, title: "What is Animation", subtitle: "Coming Soon", emoji: "✨", active: false },
          { id: "u4-58", number: 58, title: "Simple Frame Animation", subtitle: "Coming Soon", emoji: "🌀", active: false },
          { id: "u4-59", number: 59, title: "Watching Educational Videos", subtitle: "Coming Soon", emoji: "📺", active: false },
          { id: "u4-60", number: 60, title: "Creating a Slideshow", subtitle: "Coming Soon", emoji: "🖼️", active: false }
        ]
      },
      {
        id: "unit5",
        title: "Unit 5: Internet Basics",
        color: "orange",
        emoji: "🌐",
        range: "Lessons 61-75",
        lessons: [
          { id: "u5-61", number: 61, title: "What is a Website", subtitle: "Coming Soon", emoji: "🕸️", active: false },
          { id: "u5-62", number: 62, title: "Opening a Browser", subtitle: "Coming Soon", emoji: "🧭", active: false },
          { id: "u5-63", number: 63, title: "What is Google", subtitle: "Coming Soon", emoji: "🔎", active: false },
          { id: "u5-64", number: 64, title: "Searching for Pictures", subtitle: "Coming Soon", emoji: "🖼️", active: false },
          { id: "u5-65", number: 65, title: "Searching for Videos", subtitle: "Coming Soon", emoji: "🎞️", active: false },
          { id: "u5-66", number: 66, title: "Safe Searching", subtitle: "Coming Soon", emoji: "🛡️", active: false },
          { id: "u5-67", number: 67, title: "What is a Link", subtitle: "Coming Soon", emoji: "🔗", active: false },
          { id: "u5-68", number: 68, title: "Clicking Links", subtitle: "Coming Soon", emoji: "🖱️", active: false },
          { id: "u5-69", number: 69, title: "What is an Email", subtitle: "Coming Soon", emoji: "✉️", active: false },
          { id: "u5-70", number: 70, title: "What is Online Safety", subtitle: "Coming Soon", emoji: "🔒", active: false },
          { id: "u5-71", number: 71, title: "Stranger Danger Online", subtitle: "Coming Soon", emoji: "🚫", active: false },
          { id: "u5-72", number: 72, title: "Asking Before Clicking", subtitle: "Coming Soon", emoji: "🙋", active: false },
          { id: "u5-73", number: 73, title: "Good vs Bad Websites", subtitle: "Coming Soon", emoji: "⚖️", active: false },
          { id: "u5-74", number: 74, title: "What is a Password", subtitle: "Coming Soon", emoji: "🔑", active: false },
          { id: "u5-75", number: 75, title: "Keeping Information Safe", subtitle: "Coming Soon", emoji: "🧠", active: false }
        ]
      },
      {
        id: "unit6",
        title: "Unit 6: Logic & Coding Foundations",
        color: "red",
        emoji: "🧠",
        range: "Lessons 76-90",
        lessons: [
          { id: "u6-76", number: 76, title: "What is a Step-by-Step Instruction", subtitle: "Coming Soon", emoji: "👣", active: false },
          { id: "u6-77", number: 77, title: "Giving Instructions Game", subtitle: "Coming Soon", emoji: "🗣️", active: false },
          { id: "u6-78", number: 78, title: "Following Instructions Game", subtitle: "Coming Soon", emoji: "✅", active: false },
          { id: "u6-79", number: 79, title: "What is a Pattern", subtitle: "Coming Soon", emoji: "🔁", active: false },
          { id: "u6-80", number: 80, title: "Pattern Recognition Game", subtitle: "Coming Soon", emoji: "🟦", active: false },
          { id: "u6-81", number: 81, title: "Sequencing Game", subtitle: "Coming Soon", emoji: "1️⃣", active: false },
          { id: "u6-82", number: 82, title: "If / Then Thinking", subtitle: "Coming Soon", emoji: "🤔", active: false },
          { id: "u6-83", number: 83, title: "Cause and Effect", subtitle: "Coming Soon", emoji: "💡", active: false },
          { id: "u6-84", number: 84, title: "Simple Maze Logic", subtitle: "Coming Soon", emoji: "🌀", active: false },
          { id: "u6-85", number: 85, title: "Intro to Block Coding", subtitle: "Coming Soon", emoji: "🧱", active: false },
          { id: "u6-86", number: 86, title: "Move a Character", subtitle: "Coming Soon", emoji: "🏃", active: false },
          { id: "u6-87", number: 87, title: "Make a Character Jump", subtitle: "Coming Soon", emoji: "🦘", active: false },
          { id: "u6-88", number: 88, title: "Add Sound to Character", subtitle: "Coming Soon", emoji: "🔔", active: false },
          { id: "u6-89", number: 89, title: "Create a Mini Story", subtitle: "Coming Soon", emoji: "📖", active: false },
          { id: "u6-90", number: 90, title: "Build a Simple Game", subtitle: "Coming Soon", emoji: "🎮", active: false }
        ]
      }
    ],
    buildParts: [
      { id: "monitor", label: "Monitor", asset: "assets/monitor.svg", hint: "Shows pictures", zone: "monitor" },
      { id: "keyboard", label: "Keyboard", asset: "assets/keyboard.svg", hint: "Helps you type", zone: "keyboard" },
      { id: "mouse", label: "Mouse", asset: "assets/mouse.svg", hint: "Moves and clicks", zone: "mouse" },
      { id: "system", label: "Computer", asset: "assets/computer.svg", hint: "Runs the computer", zone: "system" },
    ],
    buildFunctions: [
      { id: "type", label: "Type", emoji: "✍️", target: "keyboard" },
      { id: "see", label: "See", emoji: "👀", target: "monitor" },
      { id: "click", label: "Click", emoji: "👉", target: "mouse" },
      { id: "think", label: "Brain", emoji: "⚙️", target: "system" },
    ],
    buildPrompts: [
      { clue: "Tap the part we use to TYPE.", answer: "keyboard" },
      { clue: "Tap the part that SHOWS the work.", answer: "monitor" },
      { clue: "Tap the part that MOVES the arrow.", answer: "mouse" },
      { clue: "Tap the COMPUTER.", answer: "system" },
      { clue: "Tap the part you usually look AT.", answer: "monitor" },
    ],
    sortDeck: [
      { id: "keyboard", label: "Keyboard", emoji: "⌨️", type: "input" },
      { id: "mouse", label: "Mouse", emoji: "🖱️", type: "input" },
      { id: "microphone", label: "Microphone", emoji: "🎤", type: "input" },
      { id: "webcam", label: "Webcam", emoji: "📷", type: "input" },
      { id: "touchscreen", label: "Touch Screen", emoji: "📱", type: "input" },
      { id: "speaker", label: "Speaker", emoji: "🔊", type: "output" },
      { id: "monitor", label: "Monitor", emoji: "🖥️", type: "output" },
      { id: "printer", label: "Printer", emoji: "🖨️", type: "output" },
      { id: "projector", label: "Projector", emoji: "📽️", type: "output" },
      { id: "headphones", label: "Headphones", emoji: "🎧", type: "output" },
    ],
    inputScenarios: [
      { text: "Voice in?", answer: "input" },
      { text: "Music out?", answer: "output" },
      { text: "Type name?", answer: "input" },
      { text: "See picture?", answer: "output" },
      { text: "Photo in?", answer: "input" },
      { text: "Print page?", answer: "output" },
    ],
    outputQuestions: [
      { item: "Keyboard", emoji: "⌨️", prompt: "What does it do?", correct: "Type", options: ["Type", "Hear", "Sleep"] },
      { item: "Mouse", emoji: "🖱️", prompt: "What does it do?", correct: "Move", options: ["Move", "Print", "Sing"] },
      { item: "Monitor", emoji: "🖥️", prompt: "What does it do?", correct: "See", options: ["See", "Eat", "Jump"] },
      { item: "Speaker", emoji: "🔊", prompt: "What does it do?", correct: "Hear", options: ["Hear", "Type", "Photo"] },
      { item: "Printer", emoji: "🖨️", prompt: "What does it do?", correct: "Print", options: ["Print", "Talk", "Record"] },
      { item: "Microphone", emoji: "🎤", prompt: "What does it do?", correct: "Talk", options: ["Talk", "See", "Dance"] },
      { item: "Webcam", emoji: "📷", prompt: "What does it do?", correct: "Photo", options: ["Photo", "Music", "Move"] },
      { item: "Headphones", emoji: "🎧", prompt: "What does it do?", correct: "Hear", options: ["Hear", "Print", "Food"] },
    ],
    outputScenarios: [
      { text: "Big wall video?", correct: "Projector", options: ["Projector", "Mouse", "Keyboard"] },
      { text: "Hear story?", correct: "Headphones", options: ["Headphones", "Printer", "Webcam"] },
      { text: "Paper page?", correct: "Printer", options: ["Printer", "Speaker", "Microphone"] },
      { text: "See game?", correct: "Monitor", options: ["Monitor", "Mouse", "Microphone"] },
      { text: "Play music?", correct: "Speaker", options: ["Speaker", "Keyboard", "Touch Screen"] },
      { text: "Take class photo?", correct: "Webcam", options: ["Webcam", "Printer", "Speaker"] },
    ],
    challengeRounds: [
      { says: true, prompt: "Teacher says touch the keyboard!", answer: "keyboard" },
      { says: true, prompt: "Teacher says touch something you can SEE!", answer: "monitor" },
      { says: false, prompt: "Touch the mouse!", answer: "wait" },
      { says: true, prompt: "Teacher says touch something that gives SOUND!", answer: "speaker" },
      { says: true, prompt: "Teacher says touch the microphone!", answer: "microphone" },
      { says: false, prompt: "Touch the monitor!", answer: "wait" },
      { says: true, prompt: "Teacher says touch something used to TYPE!", answer: "keyboard" },
      { says: true, prompt: "Teacher says touch the mouse!", answer: "mouse" },
      { says: false, prompt: "Touch something that prints!", answer: "wait" },
      { says: true, prompt: "Teacher says touch the printer!", answer: "printer" },
    ],
    challengeTargets: [
      { id: "keyboard", label: "Keyboard", asset: "assets/keyboard.svg" },
      { id: "mouse", label: "Mouse", asset: "assets/mouse.svg" },
      { id: "monitor", label: "Monitor", asset: "assets/monitor.svg" },
      { id: "speaker", label: "Speaker", emoji: "🔊" },
      { id: "microphone", label: "Microphone", emoji: "🎤" },
      { id: "printer", label: "Printer", emoji: "🖨️" },
      { id: "wait", label: "Wait!", emoji: "✋" },
    ],
    moodChoices: [
      { id: "happy", emoji: "😄", label: "Happy", path: "emoji" },
      { id: "excited", emoji: "🤩", label: "Excited", path: "emoji" },
      { id: "okay", emoji: "🙂", label: "Okay", path: "emoji" },
      { id: "sleepy", emoji: "😴", label: "Sleepy", path: "mindful" },
      { id: "sad", emoji: "😢", label: "Sad", path: "mindful" },
      { id: "angry", emoji: "😠", label: "Angry", path: "mindful" },
    ],
    emojiGameRounds: [
      { target: "😄", options: ["😄", "😎", "😆", "🥳"] },
      { target: "🤩", options: ["🤩", "😴", "😊", "🥰"] },
      { target: "🥳", options: ["🥳", "😢", "😄", "😮"] },
    ],
    calmSteps: [
      { id: "flower", title: "Smell the flower", emoji: "🌸", text: "Breathe in through your nose.", helper: "Smell the flower. Big slow breath in." },
      { id: "candle", title: "Blow the candle", emoji: "🕯️", text: "Breathe out very slow.", helper: "Blow the candle. Long slow breath out." },
      { id: "stretch", title: "Stretch up high", emoji: "👐", text: "Reach your hands up to the sky.", helper: "Stretch your arms. Make your body long." },
      { id: "shake", title: "Shake it out", emoji: "✨", text: "Small shake. Let the grumpy feelings go.", helper: "Shake your hands and shoulders." },
    ],
    level1Devices: [
      { id: "monitor", label: "Monitor", buttonType: "circle", hotspot: {x:"70%", y:"85%"}, fakeSpots: [{x:"20%", y:"85%"}, {x:"50%", y:"20%"}] },
      { id: "desktop", label: "PC Tower", buttonType: "square", hotspot: {x:"50%", y:"20%"}, fakeSpots: [{x:"50%", y:"50%"}, {x:"20%", y:"80%"}] },
      { id: "laptop", label: "Laptop", buttonType: "pill", hotspot: {x:"85%", y:"15%"}, fakeSpots: [{x:"10%", y:"15%"}, {x:"50%", y:"90%"}] },
      { id: "tablet", label: "Tablet", buttonType: "edge", hotspot: {x:"95%", y:"10%"}, fakeSpots: [{x:"50%", y:"90%"}, {x:"5%", y:"50%"}] },
      { id: "server", label: "Server Rack", buttonType: "rect", hotspot: {x:"80%", y:"30%"}, fakeSpots: [{x:"20%", y:"30%"}, {x:"50%", y:"70%"}] },
      { id: "printer", label: "Office Printer", buttonType: "circle", hotspot: {x:"85%", y:"20%"}, fakeSpots: [{x:"15%", y:"80%"}, {x:"50%", y:"50%"}] },
      { id: "router", label: "Wi-Fi Router", buttonType: "switch", hotspot: {x:"10%", y:"90%"}, fakeSpots: [{x:"50%", y:"10%"}, {x:"90%", y:"10%"}] },
      { id: "speakers", label: "Sound System", buttonType: "dial", hotspot: {x:"50%", y:"80%"}, fakeSpots: [{x:"50%", y:"20%"}, {x:"20%", y:"50%"}] },
      { id: "keyboard", label: "Glow Keyboard", buttonType: "key", hotspot: {x:"95%", y:"5%"}, fakeSpots: [{x:"10%", y:"95%"}, {x:"50%", y:"50%"}] },
      { id: "mouse", label: "Gaming Mouse", buttonType: "side", hotspot: {x:"5%", y:"50%"}, fakeSpots: [{x:"95%", y:"50%"}, {x:"50%", y:"10%"}] },
      { id: "projector", label: "Video Projector", buttonType: "top", hotspot: {x:"50%", y:"5%"}, fakeSpots: [{x:"50%", y:"95%"}, {x:"10%", y:"50%"}] },
      { id: "scanner", label: "Flat Scanner", buttonType: "front", hotspot: {x:"90%", y:"80%"}, fakeSpots: [{x:"10%", y:"80%"}, {x:"50%", y:"20%"}] },
      { id: "tv", label: "Smart TV", buttonType: "corner", hotspot: {x:"2%", y:"98%"}, fakeSpots: [{x:"98%", y:"2%"}, {x:"50%", y:"50%"}] },
      { id: "gamepad", label: "Game Controller", buttonType: "center", hotspot: {x:"50%", y:"40%"}, fakeSpots: [{x:"10%", y:"10%"}, {x:"90%", y:"90%"}] },
      { id: "webcam", label: "Web Camera", buttonType: "rear", hotspot: {x:"50%", y:"90%"}, fakeSpots: [{x:"50%", y:"10%"}, {x:"10%", y:"50%"}] }
    ],
    level2Operations: [
      { id: "op1", action: "tap", text: "Tap the button once!" },
      { id: "op2", action: "hold", text: "Hold the button for 3 seconds!" },
      { id: "op3", action: "tap", text: "Quick tap to wake!" },
      { id: "op4", action: "hold", text: "Long press for power!" },
      { id: "op5", action: "tap", text: "Tap to turn on lights!" },
      { id: "op6", action: "hold", text: "Hold until it beeps!" },
      { id: "op7", action: "tap", text: "Single click to start!" },
      { id: "op8", action: "hold", text: "Keep holding for bios!" },
      { id: "op9", action: "tap", text: "Touch the sensor!" },
      { id: "op10", action: "hold", text: "Firm hold to boot!" }
    ],
    level3BootTimers: [
      { id: "boot1", label: "Quick Phone", waitTime: 2000, hint: "Starting fast..." },
      { id: "boot2", label: "School Laptop", waitTime: 4000, hint: "Checking files..." },
      { id: "boot3", label: "Office PC", waitTime: 6000, hint: "Loading Windows..." },
      { id: "boot4", label: "Old Desktop", waitTime: 8000, hint: "Spinning disks..." },
      { id: "boot5", label: "Game Console", waitTime: 5000, hint: "Syncing profile..." },
      { id: "boot6", label: "Server Node", waitTime: 7000, hint: "Network boot..." },
      { id: "boot7", label: "Tablet Air", waitTime: 3000, hint: "Waking up..." },
      { id: "boot8", label: "Studio Mac", waitTime: 4500, hint: "Finalizing..." },
      { id: "boot9", label: "Kitchen Tablet", waitTime: 2500, hint: "Chef mode..." },
      { id: "boot10", label: "Mainframe", waitTime: 10000, hint: "System check..." }
    ],
    level4Logins: [
      { id: "log1", target: "Student", fakes: ["Teacher", "Guest", "Admin"] },
      { id: "log2", target: "Class 2B", fakes: ["Class 3A", "Class 1C", "Office"] },
      { id: "log3", target: "Me", fakes: ["Robot", "Cat", "Dinosaur"] },
      { id: "log4", target: "Blue Team", fakes: ["Red Team", "Green Team", "Yellow Team"] },
      { id: "log5", target: "Junior Player", fakes: ["Senior Pro", "Spectator", "Judge"] },
      { id: "log6", target: "Safe User", fakes: ["Risk User", "Unknown", "Stranger"] },
      { id: "log7", target: "Ox-Learner", fakes: ["Camb-Learner", "Stan-Learner", "Harv-Learner"] },
      { id: "log8", target: "Primary-1", fakes: ["Secondary-2", "University", "Nursery"] },
      { id: "log9", target: "I.C.T. Kid", fakes: ["Math Kid", "Art Kid", "Music Kid"] },
      { id: "log10", target: "The Winner", fakes: ["The Loser", "The Waiter", "The Thinker"] }
    ],
    level5Shutdowns: [
      { text: "School is finished! Let's shut down.", steps: ["start", "power", "shutdown"] },
      { text: "Going to the park! Turn it off.", steps: ["start", "power", "shutdown"] },
      { text: "Dinner time! Goodnight PC.", steps: ["start", "power", "shutdown"] },
      { text: "Battery is low! End session.", steps: ["start", "power", "shutdown"] },
      { text: "Teacher says freeze! Off now.", steps: ["start", "power", "shutdown"] },
      { text: "Recess time! Safely off.", steps: ["start", "power", "shutdown"] },
      { text: "Class is changing room.", steps: ["start", "power", "shutdown"] },
      { text: "Bus is here! Quick shutdown.", steps: ["start", "power", "shutdown"] },
      { text: "Finished my homework! Bye.", steps: ["start", "power", "shutdown"] },
      { text: "Cleaning the desk! Proper off.", steps: ["start", "power", "shutdown"] }
    ],
    level6Boss: [
      { id: "boss1", label: "Classroom Desktop", type: "pc" },
      { id: "boss2", label: "My Personal Tablet", type: "tablet" },
      { id: "boss3", label: "The Library Laptop", type: "laptop" }
    ],
    sillyMessages: ["Boing! Silly tap!", "Splash! A funny fish!", "Twinkle! A happy star!", "Wiggle wiggle!", "Haha! Try the game too!"],
    confettiColors: ["#ff5d8f", "#ffd84f", "#4cc9f0", "#2ec27e", "#ff8e3c", "#a78bfa"],
  };
})();
